name: Docker Build

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - "README.md"
      - "LICENSE"
      - "packagelist.alpine"
      - "alpine.Dockerfile"
  pull_request:
    branches: [ "main" ]



jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
